### ISSUE TITLE
Hand over Maintainership for PyPi (to me)

### ISSUE THREAD

**Issue by girst** [bcoe/imaplib2#26]
Hi, I need `imaplib2` for another project and sadly, this version is out of date. Since you [expressed you don't want to maintain this package any longer](https://github.com/bcoe/imaplib2/issues/23), I'd like to become the (interim?) maintainer for it on pypi and github. 

To be frank, I don't have experience with PyPi at this time, but `imaplib2` is a [slow moving target](https://sourceforge.net/p/imaplib2/code/commit_browser) I feel I can handle. 

Please let me know if you want me to take over and if so how we should continue. 

Thanks,     
tobias

**Comment by graingert** [comment]
I'm looking for any communication from the upstream maintainers on this.
Please contact them directly.

On 12 Nov 2017 14:47, "girst" <notifications@github.com> wrote:

Hi, I need imaplib2 for another project and sadly, this version is out of
date. Since you expressed you don't want to maintain this package any longer
<https://github.com/bcoe/imaplib2/issues/23>, I'd like to become the
(interim?) maintainer for it on pypi and github.

To be frank, I don't have experience with PyPi at this time, but imaplib2
is a slow moving target
<https://sourceforge.net/p/imaplib2/code/commit_browser> I feel I can
handle.

Please let me know if you want me to take over and if so how we should
continue.

Thanks,
tobias

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bcoe/imaplib2/issues/26>, or mute the thread

**Comment by johnmolyneux** [comment]
Hi,

I'm the original author of imaplib2, and I'd be delighted if someone would take over publishing it to PyPi.
I'm happy for Tobias to do it, just let me know what I need to do to enable that.
Piers Lauder

**Comment by graingert** [comment]
@johnmolyneux ah great stuff. Could you merge us into upstream, maybe move development to https://github.com/imaplib2/imaplib2  Then I can automate uploading to PyPI

**Comment by graingert** [comment]
@johnmolyneux I think that would make sense, I'd still like to keep you on board in some way and move to the https://github.com/imaplib2/imaplib2 repo.

**Comment by graingert** [comment]
@johnmolyneux rather than take a snapshot, I'll just merge the changes in.

**Comment by johnmolyneux** [comment]
Thanks. Let me know when done, and I'll add a pointer to  https://github.com/imaplib2/imaplib2

**Comment by graingert** [comment]
@johnmolyneux ok it's all on  https://github.com/imaplib2/imaplib2 now. Can you also accept the invite to the repo?

**Comment by bcoe** [comment]
@johnmolyneux 👋 thanks for the awesome work on the library over the years; was one of the building blocks of my startup Attachments.me.
